### ISSUE TITLE
Pesquisar viabilidade de realizar a interação via chatbot

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Grupo6#11]
**Descreva a solução que gostaria**

Procurar uma framework que possa ser útil para fazer um chatbot via reconhecimento de voz.

**Funcionalidades requeridas**

- [x] Adicionar links das pesquisas, caso exista código coloque referências no corpo da issue.

**Comment by baraky** [comment]
**Chatbot** trata-se da interação de um usuário com uma inteligência artificial, sendo assim é totalmente viável o desenvolvimento do projeto seguindo esse princípio.

   A idéia é automatizar o fluxo de visitantes e moradores em um condomínio, instalando um sistema que faça a comunicação por voz, permitindo (ou não) a entrada do usuário.

   Entretando essa comunicação será bastante focada e basicamente unilateral, numa sequência de perguntas (inteligência) e respostas (visitante/morador), tento um curto período de duração.


   Encontramos um framework que pode auxiliar no desenvolvimento do chatbot, o [Wit.ai.](wit.ai) Este framework possui suporte para o Português, tanto pra texto e fala, e uma documentação bastante completa.

**Comment by Bumbleblo** [comment]
Parece que o link está quebrado. Tomei a liberdade de alterar para vocês.

Gostei muito do projeto. Acredito que para quem futuramente precisar olhar o conteúdo desse trabalho encontrará muita coisa no [FAQ do projeto](https://wit.ai/faq). 

Ele preenche vários requisitos (gratis!) que a gente precisa. Acredito que é uma ótima solução. Vocês conseguiram realizar o teste dessa API ? Se sim gostaria que colocassem o teste aqui ou então dessem mais detalhes sobre. Outra coisa, vocês encontraram alguma outra API ? 

Fora essas perguntas acredito que essa tarefa já cumpriu o papel de maneira satisfatório, parabéns pelo trabalho pessoal.

**Comment by baraky** [comment]
> Parece que o link está quebrado. Tomei a liberdade de alterar para vocês.
> 
> Gostei muito do projeto. Acredito que para quem futuramente precisar olhar o conteúdo desse trabalho encontrará muita coisa no [FAQ do projeto](https://wit.ai/faq).
> 
> Ele preenche vários requisitos (gratis!) que a gente precisa. Acredito que é uma ótima solução. Vocês conseguiram realizar o teste dessa API ? Se sim gostaria que colocassem o teste aqui ou então dessem mais detalhes sobre. Outra coisa, vocês encontraram alguma outra API ?
> 
> Fora essas perguntas acredito que essa tarefa já cumpriu o papel de maneira satisfatório, parabéns pelo trabalho pessoal.

Eu tomei inciativa para tentar testar a API, mas acabei falhando por falta de conhecimento sobre APIs. Estou dando uma estudada melhor sobre para poder finalmente fazer o teste.

Infelizmente não encontrei outra API viável que possa nos ajudar no projeto.

**Comment by AlineLermen** [comment]
Comecei a testar alguns aspectos da API, mas não fui muito longe também. Utilizei como guia esse [link](https://github.com/wit-ai/pywit), que a própria documentação do Wit.ai nos direciona. Apenas gravei alguns áudios e testei os métodos "speech" e "message"

**Comment by Bumbleblo** [comment]
> > Parece que o link está quebrado. Tomei a liberdade de alterar para vocês.
> > Gostei muito do projeto. Acredito que para quem futuramente precisar olhar o conteúdo desse trabalho encontrará muita coisa no [FAQ do projeto](https://wit.ai/faq).
> > Ele preenche vários requisitos (gratis!) que a gente precisa. Acredito que é uma ótima solução. Vocês conseguiram realizar o teste dessa API ? Se sim gostaria que colocassem o teste aqui ou então dessem mais detalhes sobre. Outra coisa, vocês encontraram alguma outra API ?
> > Fora essas perguntas acredito que essa tarefa já cumpriu o papel de maneira satisfatório, parabéns pelo trabalho pessoal.
> 
> Eu tomei inciativa para tentar testar a API, mas acabei falhando por falta de conhecimento sobre APIs. Estou dando uma estudada melhor sobre para poder finalmente fazer o teste.
> 
> Infelizmente não encontrei outra API viável que possa nos ajudar no projeto.

Caso precise de ajuda pode expor aqui.
