### ISSUE TITLE
Escrever ambiente docker

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Grupo6#13]
**Descreva a solução que gostaria **

Um ambiente com docker-compose e docker para que fique mais fácil fazer o deploy da aplicação e instalar as dependências na máquina de cada um.

**Funcionalidades requeridas**

- [x] Criar uma pasta separada para os arquivos (exceto docker-compose).
- [x] Escrever o Dockerfile para o django/graphql
- [ ] Configurar o ambiente de desenvolvimento para que o /home seja um volume com as informações de dev montadas.

**Comment by Bumbleblo** [comment]
Olá  @BordaLorde como esta indo ? Precisa de alguma ajuda ? 

Se liberar um PR eu acredito que poderia ajudar com código ou com meu feedback (o que preferir).

**Comment by BordaLorde** [comment]
@Bumbleblo eu terminei ontem o ambiente docker, vou criar a branch por agora e subo. Falta criar o gitignore pra evitar que commitem o pycache etc. Se puder dar o feedback agradeço.
