### ISSUE TITLE
Planejamento 31/08

### ISSUE THREAD

**Issue by mateusnr** [fga-eps-mds/2019.2-Grupo6#16]
### Contexto

Nesse encontro a ideia é capacitar a equipe em relação ao Git flow e discutir possíveis ideias em relação ao projeto

### Tarefas

- [x]  Explicar sobre o Git flow
- [x]  Fazer um brainstorm sobre o tema do projeto

**Comment by BordaLorde** [comment]
Referência usada para o dojo de Gitflow: https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow
