### ISSUE TITLE
Pesquisar API para reconhecimento de voz

### ISSUE THREAD

**Issue by Bumbleblo** [fga-eps-mds/2019.2-Grupo6#9]
**Descreva a solução que gostaria**

Fazer uma pesquisa sobre possíveis APIs ou pacotes que possam resolver o nosso problema de verificação por voz.

**Funcionalidades requeridas**

- [x] Adicione links e as informações que encontrar no corpo da issue.

**Comment by VictorJorgeFGA** [comment]
Considerações sobre o uso do reconhecimento via voz:
        Podemos montar um sistema composto tanto de speech recognization quanto de speaker recognization. O ponto aqui é usar o speech recognization pra preencher eventuais formularios, e o speaker como uma espécie de chave ou autenticador final.

        Achei um projetinho no github que funciona para python versões 2.x. https://github.com/Atul-Anand-Jha/Speaker-Identification-Python 

        Um projeto que aparentemente parece estar em bom estado: https://github.com/ppwwyyxx/speaker-recognition 

        Outro projeto do github, porém nesse não consegui encontrar documentação e nenhum caso de uso legível para noobs pra ver como funciona, porém pra quem manjar do assunto, pode ser bom dar uma olhada. https://github.com/astorfi/3D-convolutional-speaker-recognition 

        Uma API com versão free e versão paga é o VoiceIt: https://voiceit.io/pricing . Entretanto a versão free é extremamente limitada - 1000 usos por mês - e a versão paga só séria viável se o projeto fosse vendido.

        Uma outra alternativa online para reconhecimento de speaker: Microsoft Azure https://azure.microsoft.com/pt-br/services/cognitive-services/speaker-recognition/.
O serviço pode ser utilizado com gratuidade até um certo tempo. Fica aqui como uma das últimas alternativas.

**Comment by Bumbleblo** [comment]
Show de bola @VictorJorgeFGA. Como conversamos mais cedo eu acredito que vai ser um grande problema soluções baseadas em ML e Deep Learning (acredite em mim a estrutura necessária para fazer isso funcionar esta muito além da disciplina) no entanto entendo que é muito difícil achar qualquer coisa gratuita que não use essas tecnicas.

Eu andei pesquisando também e encontrei esse [artigo](https://www.speech.kth.se/~rolf/gslt_papers/SvetoslavMarinov.pdf) explicando um pouco mais sobre. Na secção de **Text Dependent Speaker Verification** tem uma citação a uma técnica chamada **Dynamic Time Wrapping**, talvez seja interessante avaliarmos. Existe implementação em várias linguagens e o código é realmente tranquilo, assim que encontrar uma biblioteca mais estável coloco o link aqui.
